task:
  name: stable x86_64-unknown-linux
  container:
    image: rust:latest
  test_script:
    - cargo test
    - cargo test --features=fallback
  rustfmt_script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  clippy_script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features
#    - cargo clippy --all-targets --all-features -- -D warnings

task:
  name: stable x86_64-pc-windows-msvc
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
  env:
    PATH: $USERPROFILE\.cargo\bin;$PATH
  setup_script:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y --default-toolchain stable --profile=minimal
  test_script:
    - cargo test
    - cargo test --features=fallback

task:
  matrix:
  - name: stable x86_64-apple-darwin
    osx_instance:
      image: mojave-xcode
  - name: stable x86_64-unknown-freebsd-12
    freebsd_instance:
      image: freebsd-12-0-release-amd64
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --default-toolchain stable --profile=minimal
  test_script:
    - . $HOME/.cargo/env
    - cargo test
    - cargo test --features=fallback

task:
  name: nightly x86_64-unknown-redox
  container:
    image: rustlang/rust:nightly
    kvm: true
  redoxer_cache:
    folder: $HOME/.redoxer
  cargo_cache:
    folder: $HOME/.cargo
  setup_script:
    - apt update
    - apt -y install curl fuse libfuse-dev pkg-config qemu qemu-system-x86
    - cargo install --list | egrep "^\s*redoxer$" -q || cargo install redoxer
    - cargo install --list | egrep "^\s*redoxfs$" -q || cargo install redoxfs
    - redoxer install
  test_script:
    - redoxer test
    - cargo test --features=fallback
  before_cache_script:
    - rm -f $HOME/.redoxer/toolchain/rust-install.tar.gz
    - rm -rf $HOME/.cargo/registry/index
